<?php

namespace DoctrineProxies\__CG__\App\Domain\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AddressType extends \App\Domain\Entities\AddressType implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'type', 'addresses'];
        }

        return ['__isInitialized__', 'id', 'type', 'addresses'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AddressType $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\App\Domain\Entities\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', []);

        return parent::getUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsers(\App\Domain\Entities\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsers', [$user]);

        return parent::setUsers($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getSession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSession', []);

        return parent::getSession();
    }

    /**
     * {@inheritDoc}
     */
    public function setSession($session)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSession', [$session]);

        return parent::setSession($session);
    }

    /**
     * {@inheritDoc}
     */
    public function setSchool(\App\Domain\Entities\School $school)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchool', [$school]);

        return parent::setSchool($school);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchool()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchool', []);

        return parent::getSchool();
    }

    /**
     * {@inheritDoc}
     */
    public function getCourseStudent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourseStudent', []);

        return parent::getCourseStudent();
    }

    /**
     * {@inheritDoc}
     */
    public function getCourseTeacher()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourseTeacher', []);

        return parent::getCourseTeacher();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoom', []);

        return parent::getRoom();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoom(\App\Domain\Entities\Room $room)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoom', [$room]);

        return parent::setRoom($room);
    }

    /**
     * {@inheritDoc}
     */
    public function getHall()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHall', []);

        return parent::getHall();
    }

    /**
     * {@inheritDoc}
     */
    public function setHall(\App\Domain\Entities\Hall $hall)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHall', [$hall]);

        return parent::setHall($hall);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressType', []);

        return parent::getAddressType();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressType(\App\Domain\Entities\AddressType $addresstype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressType', [$addresstype]);

        return parent::setAddressType($addresstype);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity(\App\Domain\Entities\City $city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setState(\App\Domain\Entities\State $state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudent', []);

        return parent::getStudent();
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriod', []);

        return parent::getPeriod();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriod(\App\Domain\Entities\Period $period)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriod', [$period]);

        return parent::setPeriod($period);
    }

    /**
     * {@inheritDoc}
     */
    public function setStudent(\App\Domain\Entities\Student $student)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStudent', [$student]);

        return parent::setStudent($student);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuildingAddresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuildingAddresses', []);

        return parent::getBuildingAddresses();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuildingAddress(\App\Domain\Entities\BuildingAddress $buildingaddresses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuildingAddress', [$buildingaddresses]);

        return parent::setBuildingAddress($buildingaddresses);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuilding()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuilding', []);

        return parent::getBuilding();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuilding(\App\Domain\Entities\Building $building)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuilding', [$building]);

        return parent::setBuilding($building);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchoolAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchoolAddress', []);

        return parent::getSchoolAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setSchoolAddress(\App\Domain\Entities\SchoolAddress $schoodaddresses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchoolAddress', [$schoodaddresses]);

        return parent::setSchoolAddress($schoodaddresses);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', []);

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', [$fax]);

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getRollNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRollNo', []);

        return parent::getRollNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRollNo($rollno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRollNo', [$rollno]);

        return parent::setRollNo($rollno);
    }

    /**
     * {@inheritDoc}
     */
    public function getCourse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourse', []);

        return parent::getCourse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCourse(\App\Domain\Entities\Course $course)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourse', [$course]);

        return parent::setCourse($course);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeacher()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeacher', []);

        return parent::getTeacher();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeacher(\App\Domain\Entities\Teacher $teacher)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeacher', [$teacher]);

        return parent::setTeacher($teacher);
    }

    /**
     * {@inheritDoc}
     */
    public function getdescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getdescription', []);

        return parent::getdescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setdescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setdescription', [$description]);

        return parent::setdescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssignedTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssignedTo', []);

        return parent::getAssignedTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssignedTo(\App\Domain\Entities\User $assigneto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssignedTo', [$assigneto]);

        return parent::setAssignedTo($assigneto);
    }

    /**
     * {@inheritDoc}
     */
    public function getExamination()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExamination', []);

        return parent::getExamination();
    }

    /**
     * {@inheritDoc}
     */
    public function getExamMarks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExamMarks', []);

        return parent::getExamMarks();
    }

    /**
     * {@inheritDoc}
     */
    public function setExamination(\App\Domain\Entities\Examination $examination)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExamination', [$examination]);

        return parent::setExamination($examination);
    }

    /**
     * {@inheritDoc}
     */
    public function setExamMarks(\App\Domain\Entities\ExamMark $exammarks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExamMarks', [$exammarks]);

        return parent::setExamMarks($exammarks);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getSection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSection', []);

        return parent::getSection();
    }

    /**
     * {@inheritDoc}
     */
    public function setSection(\App\Domain\Entities\Section $section)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSection', [$section]);

        return parent::setSection($section);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrade', []);

        return parent::getGrade();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrade(\App\Domain\Entities\Grade $grade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrade', [$grade]);

        return parent::setGrade($grade);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubject', []);

        return parent::getSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubject(\App\Domain\Entities\Subject $subject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubject', [$subject]);

        return parent::setSubject($subject);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation($location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$location]);

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalMarks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalMarks', []);

        return parent::getTotalMarks();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalMarks($totalmarks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalMarks', [$totalmarks]);

        return parent::setTotalMarks($totalmarks);
    }

    /**
     * {@inheritDoc}
     */
    public function getExamAttendance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExamAttendance', []);

        return parent::getExamAttendance();
    }

    /**
     * {@inheritDoc}
     */
    public function setExamAttendance(\App\Domain\Entities\ExamAttendance $examattendance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExamAttendance', [$examattendance]);

        return parent::setExamAttendance($examattendance);
    }

    /**
     * {@inheritDoc}
     */
    public function getExaminationStudents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExaminationStudents', []);

        return parent::getExaminationStudents();
    }

    /**
     * {@inheritDoc}
     */
    public function setExaminationStudents(\App\Domain\Entities\ExaminationStudent $examinationstudents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExaminationStudents', [$examinationstudents]);

        return parent::setExaminationStudents($examinationstudents);
    }

}
